jdbc:
  mysql:
    url: jdbc:mysql://localhost:3306/tarotPointCounter
    username: sulyvan
    password: toto
    driver: com.mysql.cj.jdbc.Driver

spring:
  kafka:
    producer:
      api-calls-metrics-topic:
        topicName: "api-calls-metrics"
        bootstrapServers: "localhost:9092"
        groupId: "monitoring-dashboard-application"
        keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
        valueSerializer: "org.springframework.kafka.support.serializer.JsonSerializer"

metrics:
  api:
    enabled: true